### ISSUE TITLE
Dockerfile host unreachable

### ISSUE THREAD

**Issue by noumanriazkhan** [NVlabs/hymba#1]
Hi, great work folks.

I am trying to download the tar from the given url but the host is unreachable, care to upload again?

Regards

**Comment by XinDongol** [comment]
It seems that the Docker container is reachable at https://github.com/users/tilmto/packages/container/package/hymba. Would you mind sharing the detailed error message so we can troubleshoot the issue?

**Comment by noumanriazkhan** [comment]
Thank you for providing the updated url. Actually the readme still suggests `wget http://10.137.9.244:8000/hymba_docker.tar` but huggingface instructions are now updated with this url.

**Comment by XinDongol** [comment]
Updated. Thanks a lot.
